/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Gun.gltf 
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/energy-gun-739f663205ec4635a93293a3427246f8
Title: Energy gun
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Gun.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="0a411c5bd2b847df9937c76c5b81b2d0fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="down_low_z_low_polySurface490" position={[0.008, 14.816, 15.549]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="group2_down_low_polySurfaceShape117" position={[56.691, 34.987, 9.071]}>
                    <group name="group2_down_low_polySurfaceShape" position={[0.001, -0.003, 5.011]}>
                      <mesh name="group2_down_low_polySurfaceShape_2_0" geometry={nodes.group2_down_low_polySurfaceShape_2_0.geometry} material={materials.material} />
                    </group>
                    <group name="group2_down_low_polySurfaceShape79" position={[1.117, -0.048, 3.04]}>
                      <mesh name="group2_down_low_polySurfaceShape79_2_0" geometry={nodes.group2_down_low_polySurfaceShape79_2_0.geometry} material={materials.material} />
                    </group>
                    <group name="group2_down_low_polySurfaceShape106" position={[-1.554, 0.554, 3.489]}>
                      <mesh name="group2_down_low_polySurfaceShape106_2_0" geometry={nodes.group2_down_low_polySurfaceShape106_2_0.geometry} material={materials.material} />
                    </group>
                    <mesh name="group2_down_low_polySurfaceShape117_2_0" geometry={nodes.group2_down_low_polySurfaceShape117_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_f_low_polySurface478" position={[-60.468, 28.42, 9.071]}>
                    <group name="down_low_polySurface469_x_low" position={[-1.82, 0.099, 3.489]}>
                      <mesh name="down_low_polySurface469_x_low_2_0" geometry={nodes.down_low_polySurface469_x_low_2_0.geometry} material={materials.material} />
                    </group>
                    <group name="down_low_z_low_polySurface499" position={[0.001, 0.001, 5.011]}>
                      <mesh name="down_low_z_low_polySurface499_2_0" geometry={nodes.down_low_z_low_polySurface499_2_0.geometry} material={materials.material} />
                    </group>
                    <group name="down_low_v_low_polySurface516" position={[1.086, -0.218, 3.04]}>
                      <mesh name="down_low_v_low_polySurface516_2_0" geometry={nodes.down_low_v_low_polySurface516_2_0.geometry} material={materials.material} />
                    </group>
                    <mesh name="down_low_f_low_polySurface478_2_0" geometry={nodes.down_low_f_low_polySurface478_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape118" position={[3.799, -69.759, 9.071]}>
                    <group name="group2_down_low_polySurfaceShape333" position={[0.493, -0.107, 5.011]}>
                      <mesh name="group2_down_low_polySurfaceShape333_2_0" geometry={nodes.group2_down_low_polySurfaceShape333_2_0.geometry} material={materials.material} />
                    </group>
                    <group name="group2_down_low_polySurfaceShape80" position={[1.283, -0.229, 3.04]}>
                      <mesh name="group2_down_low_polySurfaceShape80_2_0" geometry={nodes.group2_down_low_polySurfaceShape80_2_0.geometry} material={materials.material} />
                    </group>
                    <group name="group2_down_low_polySurfaceShape107" position={[-1.227, 0.07, 3.489]}>
                      <mesh name="group2_down_low_polySurfaceShape107_2_0" geometry={nodes.group2_down_low_polySurfaceShape107_2_0.geometry} material={materials.material} />
                    </group>
                    <mesh name="group2_down_low_polySurfaceShape118_2_0" geometry={nodes.group2_down_low_polySurfaceShape118_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_x_low_polySurface473" position={[0.007, -2.118, 6.387]}>
                    <group name="down_low_h_low_polySurface509" position={[0, -1.531, 26.566]}>
                      <group name="down_low_z_low_polySurface491" position={[-34.43, -4.585, 53.045]} rotation={[-0.024, 0, 0]}>
                        <group name="up_low_b_low_polySurface407" position={[15.263, -42.52, 43.231]}>
                          <group name="up_low_group1_polySurfaceShape182" position={[38.798, 0, 0]}>
                            <mesh name="up_low_group1_polySurfaceShape182_1_0" geometry={nodes.up_low_group1_polySurfaceShape182_1_0.geometry} material={materials.material_1} />
                          </group>
                          <group name="up_low_group1_polySurfaceShape183" position={[59.292, 0.144, -0.062]}>
                            <mesh name="up_low_group1_polySurfaceShape183_1_0" geometry={nodes.up_low_group1_polySurfaceShape183_1_0.geometry} material={materials.material_1} />
                          </group>
                          <group name="up_low_c_low_polySurface466" position={[-20.52, 0.144, -0.062]}>
                            <mesh name="up_low_c_low_polySurface466_1_0" geometry={nodes.up_low_c_low_polySurface466_1_0.geometry} material={materials.material_1} />
                          </group>
                          <mesh name="up_low_b_low_polySurface407_1_0" geometry={nodes.up_low_b_low_polySurface407_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape167" position={[55.561, 61.609, 17.157]}>
                          <mesh name="up_low_group1_polySurfaceShape167_1_0" geometry={nodes.up_low_group1_polySurfaceShape167_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape166" position={[55.578, 84.411, 17.785]}>
                          <mesh name="up_low_group1_polySurfaceShape166_1_0" geometry={nodes.up_low_group1_polySurfaceShape166_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape165" position={[55.514, 109.135, 18.361]}>
                          <mesh name="up_low_group1_polySurfaceShape165_1_0" geometry={nodes.up_low_group1_polySurfaceShape165_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_a_low_polySurface402" position={[13.464, 109.038, 18.168]}>
                          <mesh name="up_low_a_low_polySurface402_1_0" geometry={nodes.up_low_a_low_polySurface402_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_a_low_polySurface401" position={[13.4, 84.314, 17.592]}>
                          <mesh name="up_low_a_low_polySurface401_1_0" geometry={nodes.up_low_a_low_polySurface401_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_a_low_polySurface400" position={[13.416, 61.512, 16.964]}>
                          <mesh name="up_low_a_low_polySurface400_1_0" geometry={nodes.up_low_a_low_polySurface400_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_polySurface398_a_low" position={[34.515, 45.903, 64.359]}>
                          <group name="up_low_group1_polySurfaceShape187" position={[-26.728, -28.533, -7.43]}>
                            <group name="Object_219" position={[0, 2.078, -5.641]}>
                              <mesh name="up_low_group1_polySurfaceShape187_1_0" geometry={nodes.up_low_group1_polySurfaceShape187_1_0.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="up_low_group1_polySurfaceShape188" position={[-26.728, -42.909, -7.396]}>
                            <group name="Object_222" position={[0, 2.091, -5.674]}>
                              <mesh name="up_low_group1_polySurfaceShape188_1_0" geometry={nodes.up_low_group1_polySurfaceShape188_1_0.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="up_low_group1_polySurfaceShape189" position={[-26.728, -57.266, -7.421]}>
                            <group name="Object_225" position={[0, 2.085, -5.649]}>
                              <mesh name="up_low_group1_polySurfaceShape189_1_0" geometry={nodes.up_low_group1_polySurfaceShape189_1_0.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="up_low_b_low_polySurface419" position={[-26.728, -14.174, -7.417]}>
                            <group name="Object_228" position={[0, 2.081, -5.653]}>
                              <mesh name="up_low_b_low_polySurface419_1_0" geometry={nodes.up_low_b_low_polySurface419_1_0.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="up_low_group1_polySurfaceShape194" position={[26.995, -57.265, -7.418]}>
                            <group name="Object_231" position={[0, 2.085, -5.653]}>
                              <mesh name="up_low_group1_polySurfaceShape194_1_0" geometry={nodes.up_low_group1_polySurfaceShape194_1_0.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="up_low_group1_polySurfaceShape193" position={[26.995, -42.899, -7.418]}>
                            <group name="Object_234" position={[0, 2.081, -5.652]}>
                              <mesh name="up_low_group1_polySurfaceShape193_1_0" geometry={nodes.up_low_group1_polySurfaceShape193_1_0.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="up_low_group1_polySurfaceShape195" position={[26.995, -28.531, -7.42]}>
                            <group name="Object_237" position={[0, 2.076, -5.651]}>
                              <mesh name="up_low_group1_polySurfaceShape195_1_0" geometry={nodes.up_low_group1_polySurfaceShape195_1_0.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="up_low_polySurfaceShape192_group1" position={[26.995, -14.177, -7.42]}>
                            <group name="Object_240" position={[0, 2.085, -5.651]}>
                              <mesh name="up_low_polySurfaceShape192_group1_1_0" geometry={nodes.up_low_polySurfaceShape192_group1_1_0.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="up_low_c_low_polySurface467" position={[-0.086, -62.874, 15.179]}>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface304Shape" position={[0, 58.636, 29.438]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface304Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface304Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface306Shape" position={[0, 49.55, 26.712]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface306Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface306Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface307Shape" position={[-0.001, 44.977, 25.328]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface307Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface307Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface308Shape" position={[-0.001, 40.409, 23.94]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface308Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface308Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface309Shape" position={[-0.001, 35.873, 22.555]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface309Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface309Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__polySurface303Shape_pasted__transform1_group" position={[0, 63.215, 30.835]}>
                              <mesh name="up_low_pasted__polySurface303Shape_pasted__transform1_group_1_0" geometry={nodes.up_low_pasted__polySurface303Shape_pasted__transform1_group_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface310Shape" position={[-0.001, 31.335, 21.168]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface310Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface310Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface311Shape" position={[-0.002, 26.795, 19.789]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface311Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface311Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface305Shape" position={[0, 54.083, 28.079]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface305Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface305Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_polySurface406_b_low" position={[0.097, 30.747, 12.848]}>
                              <mesh name="up_low_polySurface406_b_low_1_0" geometry={nodes.up_low_polySurface406_b_low_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface312Shape" position={[-0.002, 22.252, 18.403]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface312Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface312Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_c_low_polySurface463" position={[4.709, 63.482, 24.387]}>
                              <mesh name="up_low_c_low_polySurface463_1_0" geometry={nodes.up_low_c_low_polySurface463_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_e_low_polySurface511" position={[-0.066, 53.747, -2.289]}>
                              <mesh name="up_low_e_low_polySurface511_1_0" geometry={nodes.up_low_e_low_polySurface511_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_u_low_polySurface514" position={[0.019, 29.196, 16.571]}>
                              <mesh name="up_low_u_low_polySurface514_1_0" geometry={nodes.up_low_u_low_polySurface514_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_polySurface462_c_low" position={[-4.709, 63.482, 24.387]}>
                              <mesh name="up_low_polySurface462_c_low_1_0" geometry={nodes.up_low_polySurface462_c_low_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface315Shape" position={[-0.003, 8.589, 14.25]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface315Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface315Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface314Shape" position={[-0.002, 13.141, 15.64]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface314Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface314Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface316Shape" position={[-0.003, 4.034, 12.849]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface316Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface316Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface317Shape" position={[-0.003, -0.522, 11.462]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface317Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface317Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_pasted__transform1_group_pasted__polySurface313Shape" position={[-0.002, 17.698, 17.02]}>
                              <mesh name="up_low_pasted__transform1_group_pasted__polySurface313Shape_1_0" geometry={nodes.up_low_pasted__transform1_group_pasted__polySurface313Shape_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_c_low_polySurface468" position={[-0.003, -5.088, 10.07]}>
                              <mesh name="up_low_c_low_polySurface468_1_0" geometry={nodes.up_low_c_low_polySurface468_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_group1_polySurfaceShape198" position={[3.15, 31.054, -2.11]}>
                              <mesh name="up_low_group1_polySurfaceShape198_1_0" geometry={nodes.up_low_group1_polySurfaceShape198_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_polySurface449_d_low" position={[-2.711, 31.054, -2.11]}>
                              <mesh name="up_low_polySurface449_d_low_1_0" geometry={nodes.up_low_polySurface449_d_low_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_group1_polySurfaceShape196" position={[3.144, 31.135, -5.527]}>
                              <mesh name="up_low_group1_polySurfaceShape196_1_0" geometry={nodes.up_low_group1_polySurfaceShape196_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_d_low_polySurface451" position={[-2.706, 31.135, -5.527]}>
                              <mesh name="up_low_d_low_polySurface451_1_0" geometry={nodes.up_low_d_low_polySurface451_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_polySurface510_e_low" position={[-0.066, 31.277, -6.044]}>
                              <mesh name="up_low_polySurface510_e_low_1_0" geometry={nodes.up_low_polySurface510_e_low_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_group1_polySurfaceShape197" position={[3.145, 31.227, -8.88]}>
                              <mesh name="up_low_group1_polySurfaceShape197_1_0" geometry={nodes.up_low_group1_polySurfaceShape197_1_0.geometry} material={materials.material_1} />
                            </group>
                            <group name="up_low_d_low_polySurface453" position={[-2.707, 31.227, -8.88]}>
                              <mesh name="up_low_d_low_polySurface453_1_0" geometry={nodes.up_low_d_low_polySurface453_1_0.geometry} material={materials.material_1} />
                            </group>
                            <mesh name="up_low_c_low_polySurface467_1_0" geometry={nodes.up_low_c_low_polySurface467_1_0.geometry} material={materials.material_1} />
                          </group>
                          <group name="up_low_b_low_polySurface418" position={[-0.138, 27.273, 17.671]}>
                            <mesh name="up_low_b_low_polySurface418_1_0" geometry={nodes.up_low_b_low_polySurface418_1_0.geometry} material={materials.material_1} />
                          </group>
                          <group name="up_low_b_low_polySurface417" position={[0.133, 127.549, 20.218]}>
                            <mesh name="up_low_b_low_polySurface417_1_0" geometry={nodes.up_low_b_low_polySurface417_1_0.geometry} material={materials.material_1} />
                          </group>
                          <group name="up_low_d_low_polySurface452" position={[0.133, -109.431, 0.05]}>
                            <mesh name="up_low_d_low_polySurface452_1_0" geometry={nodes.up_low_d_low_polySurface452_1_0.geometry} material={materials.material_1} />
                          </group>
                          <mesh name="up_low_polySurface398_a_low_1_0" geometry={nodes.up_low_polySurface398_a_low_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="Plane005" position={[34.764, 192.606, 56.756]} rotation={[-3.129, 1.571, 0]} scale={[-2.191, 0, -1]}>
                          <mesh name="Plane005_Material_#7_0" geometry={nodes['Plane005_Material_#7_0'].geometry} material={materials.Material_7} />
                        </group>
                        <group name="Plane007" position={[29.446, 192.683, 50.813]} rotation={[-Math.PI, 0, -3.141]} scale={[-2.191, 0, -1]}>
                          <mesh name="Plane007_Material_#7_0" geometry={nodes['Plane007_Material_#7_0'].geometry} material={materials.Material_7} />
                        </group>
                        <group name="group2_down_low_polySurfaceShape178" position={[65.382, 15.801, 18.928]}>
                          <mesh name="group2_down_low_polySurfaceShape178_2_0" geometry={nodes.group2_down_low_polySurfaceShape178_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="group2_down_low_polySurfaceShape180" position={[72.071, 29.762, 14.049]}>
                          <mesh name="group2_down_low_polySurfaceShape180_2_0" geometry={nodes.group2_down_low_polySurfaceShape180_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="group2_down_low_polySurfaceShape186" position={[44.772, 42.389, 15.976]}>
                          <mesh name="group2_down_low_polySurfaceShape186_2_0" geometry={nodes.group2_down_low_polySurfaceShape186_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="up_low_u_low_polySurface513" position={[19.469, 114.851, 22.531]}>
                          <mesh name="up_low_u_low_polySurface513_1_0" geometry={nodes.up_low_u_low_polySurface513_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_polySurface512_u_low" position={[19.164, 102.597, 21.942]}>
                          <mesh name="up_low_polySurface512_u_low_1_0" geometry={nodes.up_low_polySurface512_u_low_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_d_low_polySurface461" position={[19.573, 57.829, 21.369]}>
                          <mesh name="up_low_d_low_polySurface461_1_0" geometry={nodes.up_low_d_low_polySurface461_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="down_low_f_low_polySurface485" position={[34.43, 42.389, 15.976]}>
                          <mesh name="down_low_f_low_polySurface485_2_0" geometry={nodes.down_low_f_low_polySurface485_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="down_low_h_low_polySurface508" position={[-3.212, 29.762, 14.049]}>
                          <mesh name="down_low_h_low_polySurface508_2_0" geometry={nodes.down_low_h_low_polySurface508_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="up_low_d_low_polySurface459" position={[19.467, 84.39, 22.03]}>
                          <mesh name="up_low_d_low_polySurface459_1_0" geometry={nodes.up_low_d_low_polySurface459_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="down_low_z_low_polySurface489" position={[34.831, -2.108, 7.726]}>
                          <mesh name="down_low_z_low_polySurface489_2_0" geometry={nodes.down_low_z_low_polySurface489_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="up_low_d_low_polySurface458" position={[34.43, 158.261, 50.366]}>
                          <mesh name="up_low_d_low_polySurface458_1_0" geometry={nodes.up_low_d_low_polySurface458_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape162" position={[49.966, 111.846, 22.814]}>
                          <mesh name="up_low_group1_polySurfaceShape162_1_0" geometry={nodes.up_low_group1_polySurfaceShape162_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_d_low_polySurface457" position={[10.749, 136.542, 35.399]}>
                          <mesh name="up_low_d_low_polySurface457_1_0" geometry={nodes.up_low_d_low_polySurface457_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="down_low_z_low_polySurface495" position={[24.087, 42.389, 15.976]}>
                          <mesh name="down_low_z_low_polySurface495_2_0" geometry={nodes.down_low_z_low_polySurface495_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="up_low_d_low_polySurface456" position={[10.749, 169.532, 36.269]}>
                          <mesh name="up_low_d_low_polySurface456_1_0" geometry={nodes.up_low_d_low_polySurface456_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="down_low_z_low_polySurface497" position={[3.477, 15.801, 18.928]}>
                          <mesh name="down_low_z_low_polySurface497_2_0" geometry={nodes.down_low_z_low_polySurface497_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="polySurfaceShape_up_low" position={[32.362, 12.827, 43.946]}>
                          <mesh name="polySurfaceShape_up_low_1_0" geometry={nodes.polySurfaceShape_up_low_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape171" position={[50.133, 102.597, 21.942]}>
                          <mesh name="up_low_group1_polySurfaceShape171_1_0" geometry={nodes.up_low_group1_polySurfaceShape171_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape168" position={[49.829, 114.851, 22.531]}>
                          <mesh name="up_low_group1_polySurfaceShape168_1_0" geometry={nodes.up_low_group1_polySurfaceShape168_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape169" position={[49.893, 90.127, 21.955]}>
                          <mesh name="up_low_group1_polySurfaceShape169_1_0" geometry={nodes.up_low_group1_polySurfaceShape169_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape172" position={[50.198, 77.874, 21.366]}>
                          <mesh name="up_low_group1_polySurfaceShape172_1_0" geometry={nodes.up_low_group1_polySurfaceShape172_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape170" position={[49.877, 67.325, 21.327]}>
                          <mesh name="up_low_group1_polySurfaceShape170_1_0" geometry={nodes.up_low_group1_polySurfaceShape170_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape173" position={[50.181, 55.071, 20.738]}>
                          <mesh name="up_low_group1_polySurfaceShape173_1_0" geometry={nodes.up_low_group1_polySurfaceShape173_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape199" position={[58.575, 169.532, 36.269]}>
                          <mesh name="up_low_group1_polySurfaceShape199_1_0" geometry={nodes.up_low_group1_polySurfaceShape199_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape163" position={[49.857, 84.39, 22.03]}>
                          <mesh name="up_low_group1_polySurfaceShape163_1_0" geometry={nodes.up_low_group1_polySurfaceShape163_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape164" position={[49.751, 57.829, 21.369]}>
                          <mesh name="up_low_group1_polySurfaceShape164_1_0" geometry={nodes.up_low_group1_polySurfaceShape164_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_d_low_polySurface460" position={[34.43, 83.651, 48.185]}>
                          <mesh name="up_low_d_low_polySurface460_1_0" geometry={nodes.up_low_d_low_polySurface460_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_d_low_polySurface450" position={[34.534, 112.133, 15.963]}>
                          <mesh name="up_low_d_low_polySurface450_1_0" geometry={nodes.up_low_d_low_polySurface450_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_d_low_polySurface454" position={[19.358, 111.846, 22.814]}>
                          <mesh name="up_low_d_low_polySurface454_1_0" geometry={nodes.up_low_d_low_polySurface454_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_c_low_polySurface465" position={[3.262, 36.889, 8.93]}>
                          <mesh name="up_low_c_low_polySurface465_1_0" geometry={nodes.up_low_c_low_polySurface465_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_c_low_polySurface464" position={[34.662, 61.757, 32.011]}>
                          <mesh name="up_low_c_low_polySurface464_1_0" geometry={nodes.up_low_c_low_polySurface464_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_b_low_polySurface420" position={[34.436, 181.381, 18.489]}>
                          <mesh name="up_low_b_low_polySurface420_1_0" geometry={nodes.up_low_b_low_polySurface420_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_b_low_polySurface416" position={[34.43, 152.965, 50.2]}>
                          <mesh name="up_low_b_low_polySurface416_1_0" geometry={nodes.up_low_b_low_polySurface416_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape200" position={[58.575, 136.542, 35.399]}>
                          <mesh name="up_low_group1_polySurfaceShape200_1_0" geometry={nodes.up_low_group1_polySurfaceShape200_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_b_low_polySurface415" position={[34.43, 69.244, 47.997]}>
                          <mesh name="up_low_b_low_polySurface415_1_0" geometry={nodes.up_low_b_low_polySurface415_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_b_low_polySurface412" position={[19.404, 90.127, 21.955]}>
                          <mesh name="up_low_b_low_polySurface412_1_0" geometry={nodes.up_low_b_low_polySurface412_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_b_low_polySurface411" position={[19.1, 77.874, 21.366]}>
                          <mesh name="up_low_b_low_polySurface411_1_0" geometry={nodes.up_low_b_low_polySurface411_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_b_low_polySurface410" position={[19.421, 67.325, 21.327]}>
                          <mesh name="up_low_b_low_polySurface410_1_0" geometry={nodes.up_low_b_low_polySurface410_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_b_low_polySurface409" position={[19.117, 55.071, 20.738]}>
                          <mesh name="up_low_b_low_polySurface409_1_0" geometry={nodes.up_low_b_low_polySurface409_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_b_low_polySurface408" position={[18.971, 74.253, 10.238]}>
                          <mesh name="up_low_b_low_polySurface408_1_0" geometry={nodes.up_low_b_low_polySurface408_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_a_low_polySurface405" position={[34.43, 191.15, 51.178]}>
                          <mesh name="up_low_a_low_polySurface405_1_0" geometry={nodes.up_low_a_low_polySurface405_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_a_low_polySurface404" position={[49.977, 107.893, 11.38]}>
                          <mesh name="up_low_a_low_polySurface404_1_0" geometry={nodes.up_low_a_low_polySurface404_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_a_low_polySurface403" position={[34.662, 163.251, 22.141]}>
                          <mesh name="up_low_a_low_polySurface403_1_0" geometry={nodes.up_low_a_low_polySurface403_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_a_low_polySurface399" position={[34.662, -52.985, 18.202]}>
                          <mesh name="up_low_a_low_polySurface399_1_0" geometry={nodes.up_low_a_low_polySurface399_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_d_low_polySurface455" position={[34.227, 178.557, 17.472]}>
                          <mesh name="up_low_d_low_polySurface455_1_0" geometry={nodes.up_low_d_low_polySurface455_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape190" position={[34.662, 150.689, 22.141]}>
                          <mesh name="up_low_group1_polySurfaceShape190_1_0" geometry={nodes.up_low_group1_polySurfaceShape190_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="up_low_group1_polySurfaceShape191" position={[34.662, 138.127, 22.141]}>
                          <mesh name="up_low_group1_polySurfaceShape191_1_0" geometry={nodes.up_low_group1_polySurfaceShape191_1_0.geometry} material={materials.material_1} />
                        </group>
                        <group name="down_low_z_low_polySurface492" position={[34.163, -38.366, -2.632]}>
                          <mesh name="down_low_z_low_polySurface492_2_0" geometry={nodes.down_low_z_low_polySurface492_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="down_low_f_low_polySurface487" position={[34.58, -6.594, 2.922]}>
                          <mesh name="down_low_f_low_polySurface487_2_0" geometry={nodes.down_low_f_low_polySurface487_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="down_low_f_low_polySurface486" position={[3.402, 16.067, 8.221]}>
                          <mesh name="down_low_f_low_polySurface486_2_0" geometry={nodes.down_low_f_low_polySurface486_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="group2_down_low_polySurfaceShape179" position={[65.457, 16.067, 8.221]}>
                          <mesh name="group2_down_low_polySurfaceShape179_2_0" geometry={nodes.group2_down_low_polySurfaceShape179_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="down_low_f_low_polySurface482" position={[7.805, -7.456, -1.123]} rotation={[-0.07, 0, 0]}>
                          <mesh name="down_low_f_low_polySurface482_2_0" geometry={nodes.down_low_f_low_polySurface482_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="down_low_f_low_polySurface481" position={[4.141, -7.456, -1.123]} rotation={[-0.07, 0, 0]}>
                          <mesh name="down_low_f_low_polySurface481_2_0" geometry={nodes.down_low_f_low_polySurface481_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="down_low_f_low_polySurface480" position={[0.843, -7.456, -1.123]} rotation={[-0.07, 0, 0]}>
                          <mesh name="down_low_f_low_polySurface480_2_0" geometry={nodes.down_low_f_low_polySurface480_2_0.geometry} material={materials.material} />
                        </group>
                        <group name="down_low_f_low_polySurface479" position={[-2.748, -7.456, -1.123]} rotation={[-0.07, 0, 0]}>
                          <mesh name="down_low_f_low_polySurface479_2_0" geometry={nodes.down_low_f_low_polySurface479_2_0.geometry} material={materials.material} />
                        </group>
                        <mesh name="down_low_z_low_polySurface491_2_0" geometry={nodes.down_low_z_low_polySurface491_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="group2_down_low_polySurfaceShape181" position={[34.43, -4.585, 53.045]}>
                        <mesh name="group2_down_low_polySurfaceShape181_2_0" geometry={nodes.group2_down_low_polySurfaceShape181_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="group2_down_low_polySurface396Shape" position={[32.366, -11.944, 51.403]}>
                        <mesh name="group2_down_low_polySurface396Shape_2_0" geometry={nodes.group2_down_low_polySurface396Shape_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_polySurface476_f_low" position={[-14.869, 9.305, 13.525]}>
                        <mesh name="down_low_polySurface476_f_low_2_0" geometry={nodes.down_low_polySurface476_f_low_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="group2_down_low_polySurfaceShape175" position={[14.869, 9.305, 13.525]}>
                        <mesh name="group2_down_low_polySurfaceShape175_2_0" geometry={nodes.group2_down_low_polySurfaceShape175_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_x_low_polySurface474" position={[-0.333, -11.261, 9.43]}>
                        <mesh name="down_low_x_low_polySurface474_2_0" geometry={nodes.down_low_x_low_polySurface474_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_z_low_polySurface494" position={[0.082, -10.61, 31.368]}>
                        <mesh name="down_low_z_low_polySurface494_2_0" geometry={nodes.down_low_z_low_polySurface494_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_v_low_polySurface517" position={[-0.021, -3.648, 8.562]}>
                        <mesh name="down_low_v_low_polySurface517_2_0" geometry={nodes.down_low_v_low_polySurface517_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_x_low_polySurface472" position={[0.329, -3.782, 41.545]}>
                        <mesh name="down_low_x_low_polySurface472_2_0" geometry={nodes.down_low_x_low_polySurface472_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="group2_down_low_polySurfaceShape184" position={[-7.499, -10.226, 9.163]}>
                        <mesh name="group2_down_low_polySurfaceShape184_2_0" geometry={nodes.group2_down_low_polySurfaceShape184_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_z_low_polySurface498" position={[7.932, -10.226, 9.647]}>
                        <mesh name="down_low_z_low_polySurface498_2_0" geometry={nodes.down_low_z_low_polySurface498_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_h_low_polySurface507" position={[-5.846, -9.624, 31.838]}>
                        <mesh name="down_low_h_low_polySurface507_2_0" geometry={nodes.down_low_h_low_polySurface507_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="group2_down_low_polySurfaceShape185" position={[5.918, -9.624, 31.838]}>
                        <mesh name="group2_down_low_polySurfaceShape185_2_0" geometry={nodes.group2_down_low_polySurfaceShape185_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_x_low_polySurface471" position={[-17.747, 6.467, 13.099]}>
                        <mesh name="down_low_x_low_polySurface471_2_0" geometry={nodes.down_low_x_low_polySurface471_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_x_low_polySurface475" position={[-17.709, 11.697, 2.699]}>
                        <mesh name="down_low_x_low_polySurface475_2_0" geometry={nodes.down_low_x_low_polySurface475_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="group2_down_low_polySurfaceShape176" position={[17.747, 6.467, 13.099]}>
                        <mesh name="group2_down_low_polySurfaceShape176_2_0" geometry={nodes.group2_down_low_polySurfaceShape176_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="group2_down_low_polySurfaceShape177" position={[17.709, 11.697, 2.699]}>
                        <mesh name="group2_down_low_polySurfaceShape177_2_0" geometry={nodes.group2_down_low_polySurfaceShape177_2_0.geometry} material={materials.material} />
                      </group>
                      <group name="down_low_z_low_polySurface496" position={[-0.109, 23.316, 31.349]}>
                        <mesh name="down_low_z_low_polySurface496_2_0" geometry={nodes.down_low_z_low_polySurface496_2_0.geometry} material={materials.material} />
                      </group>
                      <mesh name="down_low_h_low_polySurface509_2_0" geometry={nodes.down_low_h_low_polySurface509_2_0.geometry} material={materials.material} />
                    </group>
                    <group name="down_low_z_low_polySurface493" position={[-22.231, -1.269, 25.278]}>
                      <mesh name="down_low_z_low_polySurface493_2_0" geometry={nodes.down_low_z_low_polySurface493_2_0.geometry} material={materials.material} />
                    </group>
                    <group name="group2_down_low_polySurfaceShape174" position={[22.231, -1.269, 25.278]}>
                      <mesh name="group2_down_low_polySurfaceShape174_2_0" geometry={nodes.group2_down_low_polySurfaceShape174_2_0.geometry} material={materials.material} />
                    </group>
                    <mesh name="down_low_x_low_polySurface473_2_0" geometry={nodes.down_low_x_low_polySurface473_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape230" position={[0.007, -2.118, 12.661]}>
                    <group name="Object_365" position={[-30.805, -32.271, 0]}>
                      <mesh name="group2_down_low_polySurfaceShape230_2_0" geometry={nodes.group2_down_low_polySurfaceShape230_2_0.geometry} material={materials.material} />
                    </group>
                  </group>
                  <group name="group2_down_low_polySurfaceShape60" position={[0.007, -2.179, 17.908]}>
                    <group name="Object_368" position={[-35.475, -20.987, 0]}>
                      <mesh name="group2_down_low_polySurfaceShape60_2_0" geometry={nodes.group2_down_low_polySurfaceShape60_2_0.geometry} material={materials.material} />
                    </group>
                  </group>
                  <group name="group2_down_low_polySurfaceShape96" position={[98.711, 41.243, -9.216]}>
                    <mesh name="group2_down_low_polySurfaceShape96_2_0" geometry={nodes.group2_down_low_polySurfaceShape96_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape72" position={[111.217, 71.621, -6.526]}>
                    <mesh name="group2_down_low_polySurfaceShape72_2_0" geometry={nodes.group2_down_low_polySurfaceShape72_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape82" position={[73.527, 69.29, -9.237]}>
                    <mesh name="group2_down_low_polySurfaceShape82_2_0" geometry={nodes.group2_down_low_polySurfaceShape82_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape76" position={[58.676, 20.311, -10.067]}>
                    <mesh name="group2_down_low_polySurfaceShape76_2_0" geometry={nodes.group2_down_low_polySurfaceShape76_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape112" position={[92, 36.13, -9.304]}>
                    <mesh name="group2_down_low_polySurfaceShape112_2_0" geometry={nodes.group2_down_low_polySurfaceShape112_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape103" position={[82.441, 55.95, -5.056]}>
                    <mesh name="group2_down_low_polySurfaceShape103_2_0" geometry={nodes.group2_down_low_polySurfaceShape103_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape120" position={[60.771, 60.651, -8.778]}>
                    <mesh name="group2_down_low_polySurfaceShape120_2_0" geometry={nodes.group2_down_low_polySurfaceShape120_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape88" position={[66.757, 25.571, -10.138]}>
                    <mesh name="group2_down_low_polySurfaceShape88_2_0" geometry={nodes.group2_down_low_polySurfaceShape88_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="polySurfaceShape109_group2_down_low" position={[58.681, 20.303, -1.33]}>
                    <mesh name="polySurfaceShape109_group2_down_low_2_0" geometry={nodes.polySurfaceShape109_group2_down_low_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape85" position={[66.761, 25.564, -1.401]}>
                    <mesh name="group2_down_low_polySurfaceShape85_2_0" geometry={nodes.group2_down_low_polySurfaceShape85_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape91" position={[92.534, 57.829, 1.743]}>
                    <mesh name="group2_down_low_polySurfaceShape91_2_0" geometry={nodes.group2_down_low_polySurfaceShape91_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape97" position={[-12.354, -109.146, -9.216]}>
                    <mesh name="group2_down_low_polySurfaceShape97_2_0" geometry={nodes.group2_down_low_polySurfaceShape97_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape92" position={[4.608, -114.481, 1.743]}>
                    <mesh name="group2_down_low_polySurfaceShape92_2_0" geometry={nodes.group2_down_low_polySurfaceShape92_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape86" position={[-9.396, -73.769, -1.401]}>
                    <mesh name="group2_down_low_polySurfaceShape86_2_0" geometry={nodes.group2_down_low_polySurfaceShape86_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape83" position={[25.601, -101.314, -9.237]}>
                    <mesh name="group2_down_low_polySurfaceShape83_2_0" geometry={nodes.group2_down_low_polySurfaceShape83_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape73" position={[8.262, -135.298, -6.526]}>
                    <mesh name="group2_down_low_polySurfaceShape73_2_0" geometry={nodes.group2_down_low_polySurfaceShape73_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape89" position={[-9.388, -73.769, -10.138]}>
                    <mesh name="group2_down_low_polySurfaceShape89_2_0" geometry={nodes.group2_down_low_polySurfaceShape89_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape77" position={[-10.141, -64.126, -10.067]}>
                    <mesh name="group2_down_low_polySurfaceShape77_2_0" geometry={nodes.group2_down_low_polySurfaceShape77_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape110" position={[-10.15, -64.126, -1.33]}>
                    <mesh name="group2_down_low_polySurfaceShape110_2_0" geometry={nodes.group2_down_low_polySurfaceShape110_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape121" position={[27.604, -86.813, -8.778]}>
                    <mesh name="group2_down_low_polySurfaceShape121_2_0" geometry={nodes.group2_down_low_polySurfaceShape121_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape104" position={[4.042, -105.083, -5.056]}>
                    <mesh name="group2_down_low_polySurfaceShape104_2_0" geometry={nodes.group2_down_low_polySurfaceShape104_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="group2_down_low_polySurfaceShape113" position={[-15.075, -102.606, -9.304]}>
                    <mesh name="group2_down_low_polySurfaceShape113_2_0" geometry={nodes.group2_down_low_polySurfaceShape113_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_h_low_polySurface504" position={[-86.9, 62.16, -9.216]}>
                    <mesh name="down_low_h_low_polySurface504_2_0" geometry={nodes.down_low_h_low_polySurface504_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_h_low_polySurface505" position={[-98.316, 25.818, -9.237]}>
                    <mesh name="down_low_h_low_polySurface505_2_0" geometry={nodes.down_low_h_low_polySurface505_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_z_low_polySurface500" position={[-119.457, 57.324, -6.526]}>
                    <mesh name="down_low_z_low_polySurface500_2_0" geometry={nodes.down_low_z_low_polySurface500_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_h_low_polySurface503" position={[-57.347, 41.844, -10.138]}>
                    <mesh name="down_low_h_low_polySurface503_2_0" geometry={nodes.down_low_h_low_polySurface503_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_f_low_polySurface484" position={[-80.263, 58.091, -9.304]}>
                    <mesh name="down_low_f_low_polySurface484_2_0" geometry={nodes.down_low_f_low_polySurface484_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_f_low_polySurface483" position={[-85.804, 18.432, -8.778]}>
                    <mesh name="down_low_f_low_polySurface483_2_0" geometry={nodes.down_low_f_low_polySurface483_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_h_low_polySurface506" position={[-99.721, 45.779, 1.743]}>
                    <mesh name="down_low_h_low_polySurface506_2_0" geometry={nodes.down_low_h_low_polySurface506_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_x_low_polySurface470" position={[-94.646, 37.696, -5.056]}>
                    <mesh name="down_low_x_low_polySurface470_2_0" geometry={nodes.down_low_x_low_polySurface470_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_f_low_polySurface477" position={[-48.796, 37.311, -1.33]}>
                    <mesh name="down_low_f_low_polySurface477_2_0" geometry={nodes.down_low_f_low_polySurface477_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_polySurface502_h_low" position={[-57.342, 41.852, -1.401]}>
                    <mesh name="down_low_polySurface502_h_low_2_0" geometry={nodes.down_low_polySurface502_h_low_2_0.geometry} material={materials.material} />
                  </group>
                  <group name="down_low_polySurface515_v_low" position={[-48.8, 37.303, -10.067]}>
                    <mesh name="down_low_polySurface515_v_low_2_0" geometry={nodes.down_low_polySurface515_v_low_2_0.geometry} material={materials.material} />
                  </group>
                  <mesh name="down_low_z_low_polySurface490_2_0" geometry={nodes.down_low_z_low_polySurface490_2_0.geometry} material={materials.material} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Gun.gltf')
